<footer>
<div class="wrap-outer-footer layout-band">
    <div class="wrap-footer footer-slim">
        <div class="footer-main" aria-label="MIT Libraries footer">
            <div class="identity">
                <div class="wrap-logo-lib">
                    <a href="https://libraries.mit.edu" class="logo-mit-lib" alt="MIT Libraries Logo">
                        <span class="sr">MIT Libraries home</span>
                        <img src="<?php echo $this->assetUrl('img/mitlib-style/mitlib-wordmark.svg'); ?>" alt="MIT Libraries logo">
                    </a>
                </div>
                <div class="wrap-middle">
                    <div class="wrap-policies">
                        <nav aria-label="MIT Libraries policy menu">
                            <span class="item"><a href="https://libraries.mit.edu/privacy" class="link-sub">Privacy</a></span>
                            <span class="item"><a href="https://libraries.mit.edu/permissions" class="link-sub">Permissions</a></span>
                            <span class="item"><a href="https://libraries.mit.edu/accessibility" class="link-sub">Accessibility</a></span>
                        </nav>
                    </div>
                </div>
            </div><!-- end .identity -->
        </div>
    </div>
</div>
<div class="wrap-outer-footer-institute layout-band">
    <div class="wrap-footer-institute">
        <div class="footer-info-institute">
            <a class="link-logo-mit" href="https://www.mit.edu">
                <span class="sr">MIT</span>
                <svg version="1.1" xmlns="https://www.w3.org/2000/svg" x="0" y="0" width="54" height="28" viewBox="0 0 54 28" enable-background="new 0 0 54 28" xml:space="preserve" class="logo-mit"><rect x="28.9" y="8.9" width="5.8" height="19.1" class="color"/><rect width="5.8" height="28"/><rect x="9.6" width="5.8" height="18.8"/><rect x="19.3" width="5.8" height="28"/><rect x="38.5" y="8.9" width="5.8" height="19.1"/><rect x="38.8" width="15.2" height="5.6"/><rect x="28.9" width="5.8" height="5.6"/></svg>
            </a>
            <div class="about-mit">
                <span class="item">Massachusetts Institute of Technology</span>
            </div>
            <div class="license">If you are featured on this site or are a copyright owner of featured content and have copyright or privacy concerns, <a href="https://libraries.mit.edu/research-support/notices/copyright-notify/">contact us here</a>.
            </div><!-- end .footer-info-institute -->
        </div>
    </div>
</div>
</footer>
