<div class="wrap-outer-header layout-band">
  <div class="wrap-header">
    <header class="header-site header-slim" role="banner">
      <div class="wrap-header-core">
        <h1 class="name-site group nav-logo">
          <a href="https://libraries.mit.edu/" class="logo-mit-lib">
            <span class="sr">MIT Libraries home</span>
            <img src="<?php echo $this->assetUrl('img/mitlib-style/mitlib-wordmark.svg'); ?>" alt="MIT Libraries logo">
          </a>
          <a href="/" class="platform-name">Digital Exhibits</a>
        </h1>
      </div>
      <div class="wrap-header-supp">
        <a class="link-logo-mit" href="https://www.mit.edu"><img src="<?php echo $this->assetUrl('img/mitlib-style/mit_logo_std_rgb_white.svg'); ?>" alt="MIT"></a>
      </div>
    </header>
  </div>
</div>
