<?php
$sites_set = $this->themeSetting('sites_set');
$sites_page = $this->themeSetting('sites_page');

if (isset($sites_set) && isset($sites_page) && $sites_page == $page->slug()) {
    $this->headScript()->appendFile($this->assetUrl('js/sites-filter.js'));
    $this->headLink()->appendStylesheet($this->assetUrl('css/sites-filter.css'));

    ?>
    <fieldset class="site-filter-outer">
        <legend><h2>Filter exhibits by:</h2></legend>
        <span id="site-filter">
            <button class="filter-button" value="All">All</button>
        </span>
    </fieldset>
    <h3 id="filter-live" role="status" aria-live="polite" aria-atomic="true" class="sr"></h3>
    <ul id="site-grid"></ul>
    <script>
        $(document).ready(function() {
            LoadItemSet( <?php echo $sites_set; ?> );
        });
    </script>
    <?php
}
