<?php
$translate = $this->plugin('translate');
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Source+Code+Pro|Lato:400,400italic,700,700italic');
$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' · ');
$this->headLink()->appendStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
// $this->headLink()->appendStylesheet($this->assetUrl('css/style.css', 'Omeka'));
$this->headLink()->appendStylesheet($this->assetUrl('css/libraries-main.min.css'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->headScript()->appendFile($this->assetUrl('js/global.js', 'Omeka'));
$this->trigger('view.layout');
$userBar = $this->userBar();
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html')->setAttribute('lang', $this->lang()); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
        <!-- ## TODO: Replace with with something theme-aware -->
        <link rel="icon" type="image/x-icon" href="/themes/mitlibraries-theme-omeka/favicon.ico">
    </head>
    <?php echo $this->htmlElement('body')->appendAttribute('class', ''); ?>
        <a id="skip" class="skip sr sr-focusable" href="#content">Skip to main content</a>
        <?php echo $userBar; ?>
        <div class="wrap-page">
            <?php echo $this->partial('mitlib-style/header-site-slim.html'); ?>
            <div class="wrap-outer-content layout-band">
                <div class="wrap-content">
                    <div id="content-main" class="content-main" role="main">
                        <?php echo $this->messages(); ?>
                        <?php echo $this->content; ?>
                    </div>
                </div>
            </div>
            <?php echo $this->partial('mitlib-style/footer-site-slim.html'); ?>
        </div>
    </body>
</html>
