<?php
$translate = $this->plugin('translate');
$analytics_property = $this->themeSetting('analytics_property');
$banner_url = $this->themeSettingAssetUrl('banner');
$banner_text = $this->themeSetting('banner_text');

$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Source+Code+Pro|Lato:400,400italic,700,700italic');
$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' · ');
$this->headLink()->appendStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->appendStylesheet($this->assetUrl('css/libraries-main.min.css'));
$this->headLink()->appendStylesheet($this->assetUrl('css/base.css'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->headScript()->appendFile($this->assetUrl('js/global.js', 'Omeka'));
$this->trigger('view.layout');
$userBar = $this->userBar();
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html')->setAttribute('lang', $this->lang()); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
        <link rel="icon" type="image/x-icon" href="<?php echo $this->assetUrl('/img/mitlib-style/favicon.ico'); ?>">
        <?php if ($banner_url) { ?>
            <style>
                .page-banner {
                    background-image: url(<?php echo $banner_url; ?>);
                    background-position: center center;
                    background-repeat: no-repeat;
                    height: 200px;
                }
            </style>
        <?php } ?>
    </head>
    <?php echo $this->htmlElement('body')->appendAttribute('class', ''); ?>
        <a id="skip" class="skip sr sr-focusable" href="#content-main">Skip to main content</a>
        <?php echo $userBar; ?>
        <div class="wrap-page">
            <?php echo $this->partial('common/header-site-slim'); ?>
            <div class="wrap-outer-header-local layout-band">
                <div class="page-banner">
                    &nbsp;
                </div>
                <div class="wrap-content">
                    <div class="wrap-header-local">
                        <div class="page-header-home">
                            <a href="<?php echo $site->siteUrl(); ?>">
                                <p class="hd-1"><?php echo $this->escapeHtml($site->title()); ?></p>
                                <?php if ($banner_text) { ?>
                                    <p class="child-tagline"><?php echo $this->escapeHtml($banner_text); ?></p>
                                <?php } ?>
                            </a>
                        </div>
                        <div class="page-menu">
                            This would be the menu.
                        </div>
                    </div>
                </div>
            </div>
            <div class="wrap-outer-content layout-band">
                <div class="wrap-content">
                    <div id="content-main" class="content-main" role="main">
                        <?php echo $this->messages(); ?>
                        <?php echo $this->content; ?>
                    </div>
                </div>
            </div>
            <?php echo $this->partial('common/footer-site-slim'); ?>
        </div>
        <footer>
            <?php echo $this->FooterHelper($analytics_property); ?>
            <span class="powered-by"><?php echo $translate('Powered by Omeka S'); ?></span>
        </footer>
    </body>
</html>
