<?php
$translate = $this->plugin('translate');
$analytics_property = $this->themeSetting('analytics_property');

$nav_style = $this->themeSetting('nav_style');
$wrap_classes = 'wrap-content';
$content_classes = 'content-main';
if ('vertical' == $nav_style) {
    $wrap_classes .= ' layout-1q3q';
    $content_classes .= ' col3q';
}

$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Source+Code+Pro|Lato:400,400italic,700,700italic');
$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' · ');
$this->headLink()->appendStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->appendStylesheet($this->assetUrl('css/libraries-main.min.css'));
$this->headLink()->appendStylesheet($this->assetUrl('css/base.css'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->headScript()->appendFile($this->assetUrl('js/global.js', 'Omeka'));
$this->trigger('view.layout');
$userBar = $this->userBar();
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html')->setAttribute('lang', $this->lang()); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
        <link rel="icon" type="image/x-icon" href="<?php echo $this->assetUrl('/img/mitlib-style/favicon.ico'); ?>">
    </head>
    <?php echo $this->htmlElement('body')->appendAttribute('class', ''); ?>
        <a id="skip" class="skip sr sr-focusable" href="#content-main">Skip to main content</a>
        <?php echo $userBar; ?>
        <div class="wrap-page">
            <?php echo $this->partial('common/header-site-slim'); ?>
            <?php if ('default' == $nav_style) { ?>
                <?php echo $this->partial('common/navigation-default'); ?>
            <?php } ?>
            <div class="wrap-outer-content layout-band">
                <div class="<?php echo $wrap_classes; ?>">
                    <?php if ('vertical' == $nav_style) { ?>
                        <?php echo $this->partial('common/navigation-vertical'); ?>
                    <?php } ?>
                    <div id="content-main" class="<?php echo $content_classes; ?>" role="main">
                        <?php echo $this->messages(); ?>
                        <?php echo $this->content; ?>
                    </div>
                </div>
            </div>
            <?php echo $this->partial('common/footer-site-slim'); ?>
        </div>
        <footer>
            <?php echo $this->FooterHelper($analytics_property); ?>
            <span class="powered-by"><?php echo $translate('Powered by Omeka S'); ?></span>
        </footer>
    </body>
</html>
