name: manual-deploy-to-stage
on:
  workflow_dispatch:

jobs:
  deploy-theme:
    name: deploy-theme
    runs-on: [self-hosted, linux, stage]
    steps:
      - uses: actions/checkout@v4
      - name: deploy-theme
        run: |
          make deploy
          echo "Deployed theme version $(grep 'version =' config/theme.ini | awk '{print $3}')" >> $GITHUB_STEP_SUMMARY
