name: Ensure pre-built CSS

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Setup NPM
      uses: actions/setup-node@v6

    - run: npm install --production=false
      continue-on-error: true

    - run: npm list
      continue-on-error: true

    - run: npm run build
      continue-on-error: true

    - uses: CatChen/check-git-status-action@v2
      with:
        fail-if-not-clean: true
