name: Lint SCSS stylesheets

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Setup NPM
      uses: actions/setup-node@v6

    - run: npm install --production=false
      continue-on-error: true

    - run: npm list
      continue-on-error: true

    - run: npx stylelint "**/*.scss"
