name: Lint SCSS stylesheets

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: Setup NPM
      uses: actions/setup-node@v3

    - run: npm install --production=false

    - run: npm list

    - run: npx stylelint "asset/scss/**/*.scss"
