name: deploy-to-prod
on:
  release:
    types: [published]

jobs:
  deploy-theme:
    if: github.ref == 'refs/heads/main'
    name: deploy-theme
    runs-on: [self-hosted, linux, prod]
    steps:
      - name: clean-directory
        run: rm -rf repo
      - name: setup-git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      - name: clone-repo
        run: |
          git clone https://github.com/${{ github.repository }} repo
          cd repo
          git fetch --tags
          git checkout tags/${{ github.event.release.tag_name  }}
      - name: deploy-theme
        run: |
          chown -R :client .
          chmod -R g+w .
          make deploy
          echo "Deployed theme version $(grep 'version =' config/theme.ini | awk '{print $3}')" >> $GITHUB_STEP_SUMMARY
