name: deploy-to-prod
on:
  release:
    types: [published]

jobs:
  deploy-theme:
    name: deploy-theme
    runs-on: [self-hosted, linux, prod]
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: deploy-theme
        if: github.ref == 'refs/heads/main'
        run: |
          chown -R :client .
          chmod -R g+w .
          make deploy
          echo "Deployed theme version $(grep 'version =' config/theme.ini | awk '{print $3}')" >> $GITHUB_STEP_SUMMARY
