name: deploy-to-prod
on:
  release:
    types: [published]

jobs:
  deploy-theme:
    name: deploy-theme
    runs-on: [self-hosted, linux, prod]
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Exit if not main
        run: |
          if [[ "${{ github.ref }}" != "refs/heads/main" ]]; then
            echo "Branch is not main, exiting."
            exit 0
          fi

      - name: deploy-theme
        run: |
          make deploy
          echo "Deployed theme version $(grep 'version =' config/theme.ini | awk '{print $3}')" >> $GITHUB_STEP_SUMMARY
