name: deploy-to-stage
on:
  push:
    paths:
      - 'asset/**'
      - 'config/**'
      - 'helper/**'
      - 'view/**'
      - 'theme.jpg'
    branches:
      - main

jobs:
  deploy-theme:
    name: deploy-theme
    runs-on: [self-hosted, linux, stage]
    steps:
      - name: setup-git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      - name: clone-repo
        run: |
          git clone https://github.com/${{ github.repository }} repo
          cd repo
          git checkout ${{ github.ref_name }}
      - name: deploy-theme
        run: |
          chown -R :client .
          chmod -R g+w .
          make deploy
          echo "Deployed theme version $(grep 'version =' config/theme.ini | awk '{print $3}')" >> $GITHUB_STEP_SUMMARY
