name: deploy-to-stage
on:
  push:
    paths:
      - 'asset/**'
      - 'config/**'
      - 'helper/**'
      - 'view/**'
      - 'theme.jpg'
    branches:
      - main

jobs:
  deploy-theme:
    name: Deploy Theme
    runs-on: [self-hosted, Linux, stage]
    steps:
      - name: Git Checkout
        id: git-checkout
        uses: actions/checkout@v6

      - name: Deploy Theme
        id: deploy-theme
        run: make deploy

      - name: Summary
        id: summary
        run: |
          VERSION=$(grep 'version =' config/theme.ini | awk '{print $3}')
          echo "Deployed theme version $VERSION" >> $GITHUB_STEP_SUMMARY
